In [19]:
# import needed packages/libraries
import os 
import pandas as pd
import openpyxl
import numpy as np

In [20]:
# import data 
df_projectPublications = pd.read_excel('projectPublications.xlsx')
df_legalBasis = pd.read_excel('legalBasis.xlsx')
df_organization = pd.read_excel('organization.xlsx')
df_project = pd.read_excel('project.xlsx')
df_topics = pd.read_excel('topics.xlsx')

C:\Users\Marte\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\Marte\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\Marte\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\Marte\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [21]:
# Display the columns of each dataframe to check for a variable to merge on 
print(df_projectPublications.columns)
print(df_legalBasis.columns)
print(df_organization.columns)
print(df_project.columns) # does not have a projectID, merge on id?
print(df_topics.columns)

Index(['id', 'title', 'isPublishedAs', 'authors', 'journalTitle',
       'journalNumber', 'publishedYear', 'publishedPages', 'issn', 'isbn',
       'doi', 'projectID', 'projectAcronym', 'collection', 'contentUpdateDate',
       'rcn'],
      dtype='object')
Index(['projectID', 'legalBasis', 'title', 'uniqueProgrammePart'], dtype='object')
Index(['projectID', 'projectAcronym', 'organisationID', 'vatNumber', 'name',
       'shortName', 'SME', 'activityType', 'street', 'postCode', 'city',
       'country', 'nutsCode', 'geolocation', 'organizationURL', 'contactForm',
       'contentUpdateDate', 'rcn', 'order', 'role', 'ecContribution',
       'netEcContribution', 'totalCost', 'endOfParticipation', 'active'],
      dtype='object')
Index(['id', 'acronym', 'status', 'title', 'startDate', 'endDate', 'totalCost',
       'ecMaxContribution', 'legalBasis', 'topics', 'ecSignatureDate',
       'frameworkProgramme', 'masterCall', 'subCall', 'fundingScheme',
       'nature', 'objective', 'contentUpdateDate', 'rcn', 'grantDoi'],
      dtype='object')
Index(['projectID', 'topic', 'title'], dtype='object')

In [22]:
# Rename id in df_project to facilitate merging
df_project_copy = df_project.copy()
df_project_copy.rename(columns={'id': 'projectID'}, inplace=True)
df_project_copy.head()

,projectID,acronym,status,title,startDate,endDate,totalCost,ecMaxContribution,legalBasis,topics,ecSignatureDate,frameworkProgramme,masterCall,subCall,fundingScheme,nature,objective,contentUpdateDate,rcn,grantDoi
0,101159220,PvSeroRDT,SIGNED,A point-of-care serological rapid diagnostic t...,2025-02-01,2030-01-31,"4062396,23","4062396,23",HORIZON.2.1,HORIZON-JU-GH-EDCTP3-2023-02-02-two-stage,2024-12-09,HORIZON,HORIZON-JU-GH-EDCTP3-2023-02-two-stage,HORIZON-JU-GH-EDCTP3-2023-02-two-stage,HORIZON-JU-RIA,NaN,Plasmodium vivax is considered the most diffic...,2024-12-24 11:18:48,268210,10.3030/101159220
1,101096150,BIOBoost,SIGNED,Boosting innovation agencies for bioeconomy va...,2023-02-01,2025-01-31,0,500000,HORIZON.3.2,HORIZON-EIE-2022-CONNECT-01-01,2022-11-25,HORIZON,HORIZON-EIE-2022-CONNECT-01,HORIZON-EIE-2022-CONNECT-01,HORIZON-CSA,NaN,The overall objectives of the BIOBoost project...,2022-12-01 14:09:06,243343,10.3030/101096150
2,101093997,GlycanTrigger,SIGNED,GLYCANS AS MASTER TRIGGERS OF HEALTH TO INTEST...,2023-01-01,2028-12-31,6771571,6771571,HORIZON.2.1,HORIZON-HLTH-2022-STAYHLTH-02-01,2022-12-05,HORIZON,HORIZON-HLTH-2022-STAYHLTH-02,HORIZON-HLTH-2022-STAYHLTH-02,HORIZON-RIA,NaN,Chronic inflammation underlies several disease...,2022-12-11 19:02:29,243439,10.3030/101093997
3,101126531,CHIKVAX_CHIM,SIGNED,Late-stage clinical development of Chikungunya...,2023-06-01,2028-11-30,100000000,70000000,HORIZON.2.1,HORIZON-HLTH-2022-CEPI-15-01-IBA,2023-06-15,HORIZON,HORIZON-HLTH-2022-CEPI-15-IBA,HORIZON-HLTH-2022-CEPI-15-IBA,HORIZON-COFUND,NaN,A Framework Partnership Agreement (FPA) betwee...,2023-09-19 19:01:01,256925,10.3030/101126531
4,101113979,The Oater,CLOSED,The Oater develops a compact machine for hyper...,2023-07-01,2023-12-31,0,75000,HORIZON.3.2,HORIZON-EIE-2022-SCALEUP-02-02,2023-06-05,HORIZON,HORIZON-EIE-2022-SCALEUP-02,HORIZON-EIE-2022-SCALEUP-02,HORIZON-CSA,NaN,The Oater is a female-founded food tech start-...,2023-07-11 15:45:49,253030,10.3030/101113979

In [23]:
df_projectPublications['projectID'].is_unique #FALSE
df_legalBasis['projectID'].is_unique #FALSE
df_project_copy['projectID'].is_unique #TRUE
df_topics['projectID'].is_unique #TRUE
df_organization['projectID'].is_unique #FALSE

False

In [24]:
print(df_organization.head(20))
print(df_legalBasis.head(20))
print(df_projectPublications.head(20))

    projectID projectAcronym  organisationID       vatNumber  \
0   101159220      PvSeroRDT       986872084             NaN
1   101159220      PvSeroRDT       999542806             NaN
2   101159220      PvSeroRDT       889740358             NaN
3   101159220      PvSeroRDT       999912667     GB233756066
4   101159220      PvSeroRDT       999679964             NaN
5   101159220      PvSeroRDT       999993080   FR65775684897
6   101159220      PvSeroRDT       999668809     GB895149086
7   101159220      PvSeroRDT       954560414   AU12004251423
8   101096150       BIOBoost       925710480      FI26896124
9   101096150       BIOBoost       984236206      DK25666070
10  101096150       BIOBoost       995548055   FR09489228908
11  101096150       BIOBoost       914459353             NaN
12  101096150       BIOBoost       937057540      SI51545535
13  101096150       BIOBoost       999456476             NaN
14  101096150       BIOBoost       914153512    PL8133709948
15  101096150       BIOBoost       999519720    PL7010073777
16  101093997  GlycanTrigger       999990849  NL003566213B01
17  101093997  GlycanTrigger       998582700     GB718292031
18  101093997  GlycanTrigger       892061180     PT515769053
19  101093997  GlycanTrigger       999479368     PT503821012

                                                 name  \
0                      Institut Pasteur de Madagascar
1                           INSTITUT PASTEUR DE DAKAR
2                   ARMAUER HANSEN RESEARCH INSTITUTE
3   LONDON SCHOOL OF HYGIENE AND TROPICAL MEDICINE...
4           FOUNDATION FOR INNOVATIVE NEW DIAGNOSTICS
5                                    INSTITUT PASTEUR
6                         FORSITE DIAGNOSTICS LIMITED
7   THE WALTER AND ELIZA HALL INSTITUTE OF MEDICAL...
8                                  CLIC INNOVATION OY
9                                             FBCD AS
10                              BIOECONOMY FOR CHANGE
11  CLUSTER DE EMPRESAS DIGITALES SOTENIBLES E IND...
12   ITC - INOVACIJSKO TEHNOLOSKI GROZD MURSKA SOBOTA
13         VIESOJI ISTAIGA LIETUVOS INOVACIJU CENTRAS
14                                    FUNDACJA UNIMOS
15                   NARODOWE CENTRUM BADAN I ROZWOJU
16                       ACADEMISCH ZIEKENHUIS LEIDEN
17                                     LUDGER LIMITED
18  I3S - INSTITUTO DE INVESTIGACAO E INOVACAO EM ...
19  SOCIEDADE PORTUGUESA DE INOVACAO CONSULTADORIA...

                                            shortName    SME activityType  \
0                                                 IPM  False          REC
1                                                 NaN  False          REC
2                                                 NaN  False          REC
3                                               LSHTM  False          HES
4           FIND, the global alliance for diagnostics  False          OTH
5                                                  IP  False          REC
6                                                 NaN   True          PRC
7                                                WEHI  False          REC
8                                  CLIC INNOVATION OY   True          OTH
9                                                FBCD   True          OTH
10                                                B4C   True          OTH
11                                  ONTECH INNOVATION  False          REC
12  ITC - INNOVATION TECHNOLOGY CLUSTER MURSKA SOBOTA  False          REC
13                                                LIC  False          PUB
14                                             UNIMOS  False          OTH
15                                               NCBR  False          PUB
16                   Leiden University Medical Center  False          HES
17                                             LUDGER   True          PRC
18                                                NaN  False          REC
19                                                SPI   True          PRC

                                               street  postCode  ...  \
0                         Ambatofotsikely - Avaradoha       101  ...
1                                   AVENUE PASTEUR 36     DAKAR  ...
2                           JIMMA ROAD ALERT COMPOUND      1005  ...
3                                       KEPPEL STREET  WC1E 7HT  ...
4                  CAMPUS BIOTECH, CHEMIN DES MINES 9      1202  ...
5                           RUE DU DOCTEUR ROUX 25-28     75724  ...
6                                         SAND HUTTON  Y041 1LZ  ...
7                                     ROYAL PARADE 1G      3050  ...
8                                       ETELARANTA 10     00130  ...
9                              NIELS PEDERSENS ALLE 2      8830  ...
10                     10 RUE PIERRE GILLES DE GENNES     02000  ...
11                             C/ MAESTRO MONTERO, 23     18004  ...
12                                 LENDAVSKA ULICA 5A      9000  ...
13                                    T. Sevcenkos 13  LT-03223  ...
14                                  UL. GRZYBOWSKA 87    00 844  ...
15                                    UL. CHMIELNA 69    00-801  ...
16                                     ALBINUSDREEF 2   2333 ZA  ...
17                CULHAM SCIENCE CENTRE - BUILDING E1  OX14 3EB  ...
18                              RUA ALFREDO ALLEN 208  4200-135  ...
19  AV MARECHAL GOMES DA COSTA 1376 PORTO CONCELHO...  4150 356  ...

                                          contactForm    contentUpdateDate  \
0   https://ec.europa.eu/info/funding-tenders/oppo...  2024-12-24 11:18:48
1   https://ec.europa.eu/info/funding-tenders/oppo...  2024-12-24 11:18:48
2   https://ec.europa.eu/info/funding-tenders/oppo...  2024-12-24 11:18:48
3   https://ec.europa.eu/info/funding-tenders/oppo...  2024-12-24 11:18:48
4   https://ec.europa.eu/info/funding-tenders/oppo...  2024-12-24 11:18:48
5   https://ec.europa.eu/info/funding-tenders/oppo...  2024-12-24 11:18:48
6   https://ec.europa.eu/info/funding-tenders/oppo...  2024-12-24 11:18:48
7   https://ec.europa.eu/info/funding-tenders/oppo...  2024-12-24 11:18:48
8   https://ec.europa.eu/info/funding-tenders/oppo...  2022-12-01 14:09:06
9   https://ec.europa.eu/info/funding-tenders/oppo...  2022-12-01 14:09:06
10  https://ec.europa.eu/info/funding-tenders/oppo...  2022-12-01 14:09:06
11  https://ec.europa.eu/info/funding-tenders/oppo...  2022-12-01 14:09:06
12  https://ec.europa.eu/info/funding-tenders/oppo...  2022-12-01 14:09:06
13  https://ec.europa.eu/info/funding-tenders/oppo...  2022-12-01 14:09:06
14  https://ec.europa.eu/info/funding-tenders/oppo...  2022-12-01 14:09:06
15  https://ec.europa.eu/info/funding-tenders/oppo...  2022-12-01 14:09:06
16  https://ec.europa.eu/info/funding-tenders/oppo...  2022-12-11 19:02:29
17  https://ec.europa.eu/info/funding-tenders/oppo...  2022-12-11 19:02:29
18  https://ec.europa.eu/info/funding-tenders/oppo...  2022-12-11 19:02:29
19  https://ec.europa.eu/info/funding-tenders/oppo...  2022-12-11 19:02:29

        rcn order               role ecContribution netEcContribution  \
0   1947090     4  associatedPartner            NaN              0.00
1   1906512     2        participant     1777625.00        1777625.00
2   1975141     3        participant      272174.38         272174.38
3   1906028     6  associatedPartner            NaN              0.00
4   1906308     7  associatedPartner            NaN              0.00
5   1906511     1        coordinator     2012596.85        2012596.85
6   1917645     5  associatedPartner            NaN              0.00
7   1945379     8  associatedPartner            NaN              0.00
8   2573619     8        participant       68562.50          68562.50
9   2158736     1        coordinator       91812.50          91812.50
10  2136166     6        participant       65937.50          65937.50
11  1972562     5        participant       42562.50          42562.50
12  1958893     4        participant       60625.00          60625.00
13  2111621     3        participant       56312.50          56312.50
14  1966169     2        participant       73000.00          73000.00
15  1906778     7        participant       41187.50          41187.50
16  1906207     2        participant      893750.00         893750.00
17  1911950     9  associatedPartner            NaN              0.00
18  1970022     1        coordinator     3478500.00        3478500.00
19  1912321     8        participant      188750.00         188750.00

     totalCost  endOfParticipation active
0            0               False    NaN
1      1777625               False    NaN
2    272174,38               False    NaN
3            0               False    NaN
4            0               False    NaN
5   2012596,85               False    NaN
6            0               False    NaN
7            0               False    NaN
8            0               False    NaN
9            0               False    NaN
10           0               False    NaN
11           0               False    NaN
12           0               False    NaN
13           0               False    NaN
14           0               False    NaN
15           0               False    NaN
16      893750               False    NaN
17           0               False    NaN
18     3478500               False    NaN
19      188750               False    NaN

[20 rows x 25 columns]
    projectID     legalBasis  \
0   101159220    HORIZON.2.1
1   101096150    HORIZON.3.2
2   101096150  HORIZON.3.2.3
3   101093997    HORIZON.2.1
4   101093997  HORIZON.2.1.1
5   101126531    HORIZON.2.1
6   101126531  HORIZON.2.1.4
7   101113979    HORIZON.3.2
8   101113949    HORIZON.3.2
9   101103281    HORIZON.2.1
10  101145732    HORIZON.2.1
11  101113993    HORIZON.3.2
12  101114248    HORIZON.3.2
13  101114238    HORIZON.3.2
14  101114238  HORIZON.3.2.3
15  101071507    HORIZON.3.2
16  101132862  HORIZON.2.1.7
17  101132862    HORIZON.2.1
18  101114204    HORIZON.3.2
19  101132170    HORIZON.4.2

                                                title uniqueProgrammePart
0                                              Health                True
1                      European innovation ecosystems                True
2                Joint programmes close to innovators                 NaN
3                                              Health                True
4                   Health throughout the Life Course                 NaN
5                                              Health                True
6   Infectious Diseases, including poverty-related...                 NaN
7                      European innovation ecosystems                True
8                      European innovation ecosystems                True
9                                              Health                True
10                                             Health                True
11                     European innovation ecosystems                True
12                     European innovation ecosystems                True
13                     European innovation ecosystems                True
14               Joint programmes close to innovators                 NaN
15                     European innovation ecosystems                True
16                       Innovative Health Initiative                 NaN
17                                             Health                True
18                     European innovation ecosystems                True
19    Reforming and enhancing the European R&I System                True
                               id  \
0   101040480_113381_PUBLIHORIZON
1   101040480_113371_PUBLIHORIZON
2   101040480_113383_PUBLIHORIZON
3   101040480_113375_PUBLIHORIZON
4   101040480_113374_PUBLIHORIZON
5   101040480_113264_PUBLIHORIZON
6   101040480_113379_PUBLIHORIZON
7   101040480_113378_PUBLIHORIZON
8   101040480_113380_PUBLIHORIZON
9   101040480_113382_PUBLIHORIZON
10  101040480_113376_PUBLIHORIZON
11  101040480_113377_PUBLIHORIZON
12  101040480_113373_PUBLIHORIZON
13  101040480_113372_PUBLIHORIZON
14  101040480_113384_PUBLIHORIZON
15  101078482_120681_PUBLIHORIZON
16  101055141_124073_PUBLIHORIZON
17  101053021_128014_PUBLIHORIZON
18  101063410_111303_PUBLIHORIZON
19  101054957_132216_PUBLIHORIZON

                                                title           isPublishedAs  \
0   The Microwave Rotational Electric Resonance (R...  Peer reviewed articles
1   The microwave spectra of the conformers of n-b...  Peer reviewed articles
2   Coupled internal rotations and 14N quadrupole ...  Peer reviewed articles
3   The Heavy Atom Structure, <i>“cis</i> effect” ...  Peer reviewed articles
4   Structure determination of 2,5-difluorophenol ...  Peer reviewed articles
5   Low barriers to internal rotation in the micro...  Peer reviewed articles
6   Coupled methyl internal rotations with interme...  Peer reviewed articles
7   Barrier to Methyl Internal Rotation and Equili...  Peer reviewed articles
8   Revealing Internal Rotation and 14N Nuclear Qu...  Peer reviewed articles
9   Surprising torsional barrier reduction in the ...  Peer reviewed articles
10  Quantum Tunneling: History and Mystery of Larg...  Peer reviewed articles
11  Approaching the free rotor limit: extremely lo...  Peer reviewed articles
12  A global rho-axis method for fitting asymmetri...  Peer reviewed articles
13  Low Barrier Methyl Internal Rotations and <sup...  Peer reviewed articles
14  Benchmarking quantum chemical methods for accu...  Peer reviewed articles
15  Stronger 3-SUM Lower Bounds for Approximate Di...  Conference proceedings
16  SPOT: A machine learning model that predicts s...  Peer reviewed articles
17  Holomorphically conjugate polynomial automorph...  Peer reviewed articles
18  Harnessing Ti3C2-WS2 nanostructures as efficie...  Peer reviewed articles
19  Integrating single-cell RNA-seq datasets with ...                   Other

                                              authors  \
0   Hamza El Hadki, Kenneth J. Koziol, Oum Keltoum...
1   Susanna L. Stephens, Eléonore Antonelli, Alexa...
2    Mike Barth, Isabelle Kleiner, Ha Vinh Lam Nguyen
3   Truong Anh Nguyen, Isabelle Kleiner, Martin Sc...
4   K.P. Rajappan Nair, Kevin G. Lengsfeld, Philip...
5   Haoyue Sun, Safa Khemissi, Isabelle Kleiner, H...
6   Haoyue Sun, Lynn Ferres, Isabelle Kleiner, Ha ...
7   Kenneth J. Koziol, Hamza El Hadki, Arne Lüchow...
8   Shefali Baweja, Eleonore Antonelli, Safia Huss...
9   Mike Buttkus-Barth, Thi Ha Nguyen, Gregor Bran...
10                                 Ha Vinh Lam Nguyen
11  Safa Khemissi, Martin Schwell, Isabelle Kleine...
12  Eléonore Antonelli, Eva Gougoula, Nicholas R. ...
13  Safa Khemissi, Vinh Van, Martin Schwell, Isabe...
14  Lilian W. Sutikdja, Ha Vinh Lam Nguyen, Dragan...
15                         Abboud, Bringmann, Fischer
16  Alexander Kroll, Nico Niebuhr, Gregory Butler,...
17                      Serge Cantat; Romain Dujardin
18  Amutha Subramani, Levna Chacko, Bing Wu, Vlast...
19  Karin Hrovatin; Amir Ali Moinfar; Luke Zappia;...

                                   journalTitle journalNumber  publishedYear  \
0                                     Molecules            28           2023
1             Journal of Molecular Spectroscopy           397           2024
2               The Journal of Chemical Physics           160           2024
3                                  ChemPhysChem            25           2024
4                Journal of Molecular Structure          1321           2024
5               The Journal of Chemical Physics           160           2024
6               The Journal of Chemical Physics           161           2024
7                          Spectroscopy Journal             1           2023
8                                     Molecules            28           2023
9           Physical Chemistry Chemical Physics            26           2024
10    The Journal of Physical Chemistry Letters           NaN           2024
11          Physical Chemistry Chemical Physics            26           2024
12              The Journal of Chemical Physics           160           2024
13          The Journal of Physical Chemistry A           127           2023
14          Physical Chemistry Chemical Physics            25           2023
15                                    STOC 2023           NaN           2023
16                                 PLOS Biology            22           2024
17  Bulletin of the London Mathematical Society           NaN           2024
18               Materials Today Sustainability           NaN           2024
19                                      bioRxiv           NaN           2024

   publishedPages       issn isbn                             doi  projectID  \
0             NaN  1420-3049  NaN       10.3390/molecules28083419  101040480
1             NaN  0022-2852  NaN       10.1016/j.jms.2023.111824  101040480
2             NaN  0021-9606  NaN               10.1063/5.0213319  101040480
3             NaN  1439-4235  NaN          10.1002/cphc.202400387  101040480
4             NaN  0022-2860  NaN  10.1016/j.molstruc.2024.139971  101040480
5             NaN  0021-9606  NaN               10.1063/5.0185005  101040480
6             NaN  0021-9606  NaN               10.1063/5.0235431  101040480
7             NaN  2813-446X  NaN       10.3390/spectroscj1010005  101040480
8             NaN  1420-3049  NaN       10.3390/molecules28052153  101040480
9             NaN  1463-9076  NaN              10.1039/x0xx00000x  101040480
10            NaN  1948-7185  NaN     10.1021/acs.jpclett.4c02914  101040480
11            NaN  1463-9076  NaN              10.1039/D3CP04748B  101040480
12            NaN  0021-9606  NaN               10.1063/5.0207944  101040480
13            NaN  1089-5639  NaN        10.1021/acs.jpca.3c01008  101040480
14            NaN  1463-9076  NaN              10.1039/D2CP05774C  101040480
15            NaN        NaN  NaN         10.1145/3564246.3585240  101078482
16            NaN  1545-7885  NaN    10.1371/journal.pbio.3002807  101055141
17            NaN  1469-2120  NaN              10.1112/blms.13164  101053021
18            NaN  2589-2347  NaN         10.5281/zenodo.13897774  101063410
19            NaN        NaN  NaN       10.1101/2023.11.03.565463  101054957

   projectAcronym           collection    contentUpdateDate      rcn
0         LACRIDO  Project publication  2025-02-11 11:41:50  1243351
1         LACRIDO  Project publication  2025-02-11 11:01:16  1243327
2         LACRIDO  Project publication  2025-02-11 11:40:00  1243350
3         LACRIDO  Project publication  2025-02-11 11:11:17  1243343
4         LACRIDO  Project publication  2025-02-11 11:04:26  1243340
5         LACRIDO  Project publication  2025-02-11 11:02:01  1243337
6         LACRIDO  Project publication  2025-02-11 11:20:35  1243345
7         LACRIDO  Project publication  2025-02-11 11:23:22  1243346
8         LACRIDO  Project publication  2025-02-11 11:28:00  1243348
9         LACRIDO  Project publication  2025-02-11 11:43:11  1243353
10        LACRIDO  Project publication  2025-02-11 11:08:42  1243341
11        LACRIDO  Project publication  2025-02-11 11:20:00  1243344
12        LACRIDO  Project publication  2025-02-11 11:10:33  1243342
13        LACRIDO  Project publication  2025-02-11 11:00:14  1243321
14        LACRIDO  Project publication  2025-02-11 13:07:44  1243349
15      CONJEXITY  Project publication  2025-02-24 09:17:57  1256166
16        MECHSYS  Project publication  2025-02-17 12:46:10  1254102
17           GOAT  Project publication  2025-03-04 16:00:57  1259593
18        2DTMCH2  Project publication  2025-03-03 11:10:50  1258833
19       DeepCell  Project publication  2025-03-17 09:36:38  1270204

In [25]:
# Rename id in df_project to facilitate merging
df_project_copy = df_project.copy()
df_project_copy.rename(columns={'id': 'projectID'}, inplace=True)
df_project_copy.head()

,projectID,acronym,status,title,startDate,endDate,totalCost,ecMaxContribution,legalBasis,topics,ecSignatureDate,frameworkProgramme,masterCall,subCall,fundingScheme,nature,objective,contentUpdateDate,rcn,grantDoi
0,101159220,PvSeroRDT,SIGNED,A point-of-care serological rapid diagnostic t...,2025-02-01,2030-01-31,"4062396,23","4062396,23",HORIZON.2.1,HORIZON-JU-GH-EDCTP3-2023-02-02-two-stage,2024-12-09,HORIZON,HORIZON-JU-GH-EDCTP3-2023-02-two-stage,HORIZON-JU-GH-EDCTP3-2023-02-two-stage,HORIZON-JU-RIA,NaN,Plasmodium vivax is considered the most diffic...,2024-12-24 11:18:48,268210,10.3030/101159220
1,101096150,BIOBoost,SIGNED,Boosting innovation agencies for bioeconomy va...,2023-02-01,2025-01-31,0,500000,HORIZON.3.2,HORIZON-EIE-2022-CONNECT-01-01,2022-11-25,HORIZON,HORIZON-EIE-2022-CONNECT-01,HORIZON-EIE-2022-CONNECT-01,HORIZON-CSA,NaN,The overall objectives of the BIOBoost project...,2022-12-01 14:09:06,243343,10.3030/101096150
2,101093997,GlycanTrigger,SIGNED,GLYCANS AS MASTER TRIGGERS OF HEALTH TO INTEST...,2023-01-01,2028-12-31,6771571,6771571,HORIZON.2.1,HORIZON-HLTH-2022-STAYHLTH-02-01,2022-12-05,HORIZON,HORIZON-HLTH-2022-STAYHLTH-02,HORIZON-HLTH-2022-STAYHLTH-02,HORIZON-RIA,NaN,Chronic inflammation underlies several disease...,2022-12-11 19:02:29,243439,10.3030/101093997
3,101126531,CHIKVAX_CHIM,SIGNED,Late-stage clinical development of Chikungunya...,2023-06-01,2028-11-30,100000000,70000000,HORIZON.2.1,HORIZON-HLTH-2022-CEPI-15-01-IBA,2023-06-15,HORIZON,HORIZON-HLTH-2022-CEPI-15-IBA,HORIZON-HLTH-2022-CEPI-15-IBA,HORIZON-COFUND,NaN,A Framework Partnership Agreement (FPA) betwee...,2023-09-19 19:01:01,256925,10.3030/101126531
4,101113979,The Oater,CLOSED,The Oater develops a compact machine for hyper...,2023-07-01,2023-12-31,0,75000,HORIZON.3.2,HORIZON-EIE-2022-SCALEUP-02-02,2023-06-05,HORIZON,HORIZON-EIE-2022-SCALEUP-02,HORIZON-EIE-2022-SCALEUP-02,HORIZON-CSA,NaN,The Oater is a female-founded food tech start-...,2023-07-11 15:45:49,253030,10.3030/101113979

In [ ]:
agg_organizations = df_organization.groupby('projectID').agg(lambda x: '; '.join(x.dropna().astype(str))).reset_index()
agg_legalBasis = df_legalBasis.groupby('projectID').agg(lambda x: '; '.join(x.dropna().astype(str))).reset_index()
agg_publications = df_projectPublications.groupby('projectID').agg(lambda x: '; '.join(x.dropna().astype(str))).reset_index()

# 4. Merge everything into df_project_copy
merged_all = df_project_copy.copy()

merged_all = merged_all.merge(agg_organizations, on='projectID', how='left')
merged_all = merged_all.merge(agg_legalBasis, on='projectID', how='left')
merged_all = merged_all.merge(agg_publications, on='projectID', how='left')

# 5. Check result
print("Merged DataFrame shape:", merged_all.shape)
merged_all.head()

✅ Merged DataFrame shape: (15863, 62)

,projectID,acronym,status,title_x,startDate,endDate,totalCost_x,ecMaxContribution,legalBasis_x,topics,...,journalNumber,publishedYear,publishedPages,issn,isbn,doi,projectAcronym_y,collection,contentUpdateDate,rcn
0,101159220,PvSeroRDT,SIGNED,A point-of-care serological rapid diagnostic t...,2025-02-01,2030-01-31,"4062396,23","4062396,23",HORIZON.2.1,HORIZON-JU-GH-EDCTP3-2023-02-02-two-stage,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,101096150,BIOBoost,SIGNED,Boosting innovation agencies for bioeconomy va...,2023-02-01,2025-01-31,0,500000,HORIZON.3.2,HORIZON-EIE-2022-CONNECT-01-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,101093997,GlycanTrigger,SIGNED,GLYCANS AS MASTER TRIGGERS OF HEALTH TO INTEST...,2023-01-01,2028-12-31,6771571,6771571,HORIZON.2.1,HORIZON-HLTH-2022-STAYHLTH-02-01,...,544; 73,2024; 2024; 2023; 2024; 2023; 2023; 2023,,0008-6215; 1044-5323; 1672-7681; 1529-2908; 14...,,10.1016/j.carres.2024.109245; 10.1016/j.smim.2...,GlycanTrigger; GlycanTrigger; GlycanTrigger; G...,Project publication; Project publication; Proj...,2024-12-02 13:26:45; 2024-12-02 13:26:45; 2024...,1214252; 1214256; 1055021; 1217756; 970198; 97...
3,101126531,CHIKVAX_CHIM,SIGNED,Late-stage clinical development of Chikungunya...,2023-06-01,2028-11-30,100000000,70000000,HORIZON.2.1,HORIZON-HLTH-2022-CEPI-15-01-IBA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,101113979,The Oater,CLOSED,The Oater develops a compact machine for hyper...,2023-07-01,2023-12-31,0,75000,HORIZON.3.2,HORIZON-EIE-2022-SCALEUP-02-02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
print(merged_all.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15863 entries, 0 to 15862
Data columns (total 62 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   projectID            15863 non-null  int64
 1   acronym              15863 non-null  object
 2   status               15863 non-null  object
 3   title_x              15863 non-null  object
 4   startDate            15863 non-null  object
 5   endDate              15863 non-null  object
 6   totalCost_x          15863 non-null  object
 7   ecMaxContribution    15863 non-null  object
 8   legalBasis_x         15863 non-null  object
 9   topics               15863 non-null  object
 10  ecSignatureDate      15862 non-null  object
 11  frameworkProgramme   15863 non-null  object
 12  masterCall           15863 non-null  object
 13  subCall              15863 non-null  object
 14  fundingScheme        15863 non-null  object
 15  nature               0 non-null      float64
 16  objective            15863 non-null  object
 17  contentUpdateDate_x  15863 non-null  object
 18  rcn_x                15863 non-null  int64
 19  grantDoi             15802 non-null  object
 20  projectAcronym_x     15863 non-null  object
 21  organisationID       15863 non-null  object
 22  vatNumber            15863 non-null  object
 23  name                 15863 non-null  object
 24  shortName            15863 non-null  object
 25  SME                  15863 non-null  object
 26  activityType         15863 non-null  object
 27  street               15863 non-null  object
 28  postCode             15863 non-null  object
 29  city                 15863 non-null  object
 30  country              15863 non-null  object
 31  nutsCode             15863 non-null  object
 32  geolocation          15863 non-null  object
 33  organizationURL      15863 non-null  object
 34  contactForm          15863 non-null  object
 35  contentUpdateDate_y  15863 non-null  object
 36  rcn_y                15863 non-null  object
 37  order                15863 non-null  object
 38  role                 15863 non-null  object
 39  ecContribution       15863 non-null  object
 40  netEcContribution    15863 non-null  object
 41  totalCost_y          15863 non-null  object
 42  endOfParticipation   15863 non-null  object
 43  active               15863 non-null  object
 44  legalBasis_y         15863 non-null  object
 45  title_y              15863 non-null  object
 46  uniqueProgrammePart  15863 non-null  object
 47  id                   3969 non-null   object
 48  title                3969 non-null   object
 49  isPublishedAs        3969 non-null   object
 50  authors              3969 non-null   object
 51  journalTitle         3969 non-null   object
 52  journalNumber        3969 non-null   object
 53  publishedYear        3969 non-null   object
 54  publishedPages       3969 non-null   object
 55  issn                 3969 non-null   object
 56  isbn                 3969 non-null   object
 57  doi                  3969 non-null   object
 58  projectAcronym_y     3969 non-null   object
 59  collection           3969 non-null   object
 60  contentUpdateDate    3969 non-null   object
 61  rcn                  3969 non-null   object
dtypes: float64(1), int64(2), object(59)
memory usage: 7.5+ MB
None

In [ ]:
# merge other two dataframes 
# First merge: df_topics
merged_all = merged_all.merge(
    df_topics,
    on='projectID',
    how='left',
    suffixes=('', '_topics')  # prevent duplicate column names
)

# Then merge: df_webLink
merged_all = merged_all.merge(
    df_project_copy,
    on='projectID',
    how='left',
    suffixes=('', '_project')  # avoid duplicate suffix errors
)

# Check the final shape and preview
print("Final merged shape:", merged_all.shape)
merged_all.head()

✅ Final merged shape: (15863, 83)

,projectID,acronym,status,title_x,startDate,endDate,totalCost_x,ecMaxContribution,legalBasis_x,topics,...,ecSignatureDate_project,frameworkProgramme_project,masterCall_project,subCall_project,fundingScheme_project,nature_project,objective_project,contentUpdateDate_project,rcn_project,grantDoi_project
0,101159220,PvSeroRDT,SIGNED,A point-of-care serological rapid diagnostic t...,2025-02-01,2030-01-31,"4062396,23","4062396,23",HORIZON.2.1,HORIZON-JU-GH-EDCTP3-2023-02-02-two-stage,...,2024-12-09,HORIZON,HORIZON-JU-GH-EDCTP3-2023-02-two-stage,HORIZON-JU-GH-EDCTP3-2023-02-two-stage,HORIZON-JU-RIA,NaN,Plasmodium vivax is considered the most diffic...,2024-12-24 11:18:48,268210,10.3030/101159220
1,101096150,BIOBoost,SIGNED,Boosting innovation agencies for bioeconomy va...,2023-02-01,2025-01-31,0,500000,HORIZON.3.2,HORIZON-EIE-2022-CONNECT-01-01,...,2022-11-25,HORIZON,HORIZON-EIE-2022-CONNECT-01,HORIZON-EIE-2022-CONNECT-01,HORIZON-CSA,NaN,The overall objectives of the BIOBoost project...,2022-12-01 14:09:06,243343,10.3030/101096150
2,101093997,GlycanTrigger,SIGNED,GLYCANS AS MASTER TRIGGERS OF HEALTH TO INTEST...,2023-01-01,2028-12-31,6771571,6771571,HORIZON.2.1,HORIZON-HLTH-2022-STAYHLTH-02-01,...,2022-12-05,HORIZON,HORIZON-HLTH-2022-STAYHLTH-02,HORIZON-HLTH-2022-STAYHLTH-02,HORIZON-RIA,NaN,Chronic inflammation underlies several disease...,2022-12-11 19:02:29,243439,10.3030/101093997
3,101126531,CHIKVAX_CHIM,SIGNED,Late-stage clinical development of Chikungunya...,2023-06-01,2028-11-30,100000000,70000000,HORIZON.2.1,HORIZON-HLTH-2022-CEPI-15-01-IBA,...,2023-06-15,HORIZON,HORIZON-HLTH-2022-CEPI-15-IBA,HORIZON-HLTH-2022-CEPI-15-IBA,HORIZON-COFUND,NaN,A Framework Partnership Agreement (FPA) betwee...,2023-09-19 19:01:01,256925,10.3030/101126531
4,101113979,The Oater,CLOSED,The Oater develops a compact machine for hyper...,2023-07-01,2023-12-31,0,75000,HORIZON.3.2,HORIZON-EIE-2022-SCALEUP-02-02,...,2023-06-05,HORIZON,HORIZON-EIE-2022-SCALEUP-02,HORIZON-EIE-2022-SCALEUP-02,HORIZON-CSA,NaN,The Oater is a female-founded food tech start-...,2023-07-11 15:45:49,253030,10.3030/101113979

In [29]:
print(merged_all.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15863 entries, 0 to 15862
Data columns (total 83 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   projectID                   15863 non-null  int64
 1   acronym                     15863 non-null  object
 2   status                      15863 non-null  object
 3   title_x                     15863 non-null  object
 4   startDate                   15863 non-null  object
 5   endDate                     15863 non-null  object
 6   totalCost_x                 15863 non-null  object
 7   ecMaxContribution           15863 non-null  object
 8   legalBasis_x                15863 non-null  object
 9   topics                      15863 non-null  object
 10  ecSignatureDate             15862 non-null  object
 11  frameworkProgramme          15863 non-null  object
 12  masterCall                  15863 non-null  object
 13  subCall                     15863 non-null  object
 14  fundingScheme               15863 non-null  object
 15  nature                      0 non-null      float64
 16  objective                   15863 non-null  object
 17  contentUpdateDate_x         15863 non-null  object
 18  rcn_x                       15863 non-null  int64
 19  grantDoi                    15802 non-null  object
 20  projectAcronym_x            15863 non-null  object
 21  organisationID              15863 non-null  object
 22  vatNumber                   15863 non-null  object
 23  name                        15863 non-null  object
 24  shortName                   15863 non-null  object
 25  SME                         15863 non-null  object
 26  activityType                15863 non-null  object
 27  street                      15863 non-null  object
 28  postCode                    15863 non-null  object
 29  city                        15863 non-null  object
 30  country                     15863 non-null  object
 31  nutsCode                    15863 non-null  object
 32  geolocation                 15863 non-null  object
 33  organizationURL             15863 non-null  object
 34  contactForm                 15863 non-null  object
 35  contentUpdateDate_y         15863 non-null  object
 36  rcn_y                       15863 non-null  object
 37  order                       15863 non-null  object
 38  role                        15863 non-null  object
 39  ecContribution              15863 non-null  object
 40  netEcContribution           15863 non-null  object
 41  totalCost_y                 15863 non-null  object
 42  endOfParticipation          15863 non-null  object
 43  active                      15863 non-null  object
 44  legalBasis_y                15863 non-null  object
 45  title_y                     15863 non-null  object
 46  uniqueProgrammePart         15863 non-null  object
 47  id                          3969 non-null   object
 48  title                       3969 non-null   object
 49  isPublishedAs               3969 non-null   object
 50  authors                     3969 non-null   object
 51  journalTitle                3969 non-null   object
 52  journalNumber               3969 non-null   object
 53  publishedYear               3969 non-null   object
 54  publishedPages              3969 non-null   object
 55  issn                        3969 non-null   object
 56  isbn                        3969 non-null   object
 57  doi                         3969 non-null   object
 58  projectAcronym_y            3969 non-null   object
 59  collection                  3969 non-null   object
 60  contentUpdateDate           3969 non-null   object
 61  rcn                         3969 non-null   object
 62  topic                       15863 non-null  object
 63  title_topics                15863 non-null  object
 64  acronym_project             15863 non-null  object
 65  status_project              15863 non-null  object
 66  title_project               15863 non-null  object
 67  startDate_project           15863 non-null  object
 68  endDate_project             15863 non-null  object
 69  totalCost                   15863 non-null  object
 70  ecMaxContribution_project   15863 non-null  object
 71  legalBasis                  15863 non-null  object
 72  topics_project              15863 non-null  object
 73  ecSignatureDate_project     15862 non-null  object
 74  frameworkProgramme_project  15863 non-null  object
 75  masterCall_project          15863 non-null  object
 76  subCall_project             15863 non-null  object
 77  fundingScheme_project       15863 non-null  object
 78  nature_project              0 non-null      float64
 79  objective_project           15863 non-null  object
 80  contentUpdateDate_project   15863 non-null  object
 81  rcn_project                 15863 non-null  int64
 82  grantDoi_project            15802 non-null  object
dtypes: float64(2), int64(3), object(78)
memory usage: 10.0+ MB
None

INVESTIGATE DUPLICATE COLUMNS

In [31]:
# title
columns_to_compare_title = [
    'title', 
    'title_x', 
    'title_y', 
    'title_topics', 
    'title_project'
] 

print(merged_all[columns_to_compare_title].head(10)) #drop: title, title_y, title_topics, title_project

                                               title  \
0                                                NaN
1                                                NaN
2  “Glycans in Trained Immunity: Educators of inn...
3                                                NaN
4                                                NaN
5                         Journal of Dental Sciences
6                                                NaN
7                                                NaN
8                                                NaN
9                                                NaN

                                             title_x  \
0  A point-of-care serological rapid diagnostic t...
1  Boosting innovation agencies for bioeconomy va...
2  GLYCANS AS MASTER TRIGGERS OF HEALTH TO INTEST...
3  Late-stage clinical development of Chikungunya...
4  The Oater develops a compact machine for hyper...
5  A System for the Early Diagnosis of Skeletal O...
6  EPiTB: Addressing an unmet need: same day diag...
7  Côte d'Ivoire Ethics Capacity Building Initiat...
8  Producing Green Hydrogen Using Power of Ocean ...
9        Elia - Smart Assistant for English Learning

                                             title_y  \
0                                             Health
1  European innovation ecosystems; Joint programm...
2          Health; Health throughout the Life Course
3  Health; Infectious Diseases, including poverty...
4                     European innovation ecosystems
5                     European innovation ecosystems
6                                             Health
7                                             Health
8                     European innovation ecosystems
9                     European innovation ecosystems

                                        title_topics  \
0  Advancing point-of-care diagnostics to the market
1  Towards more inclusive networks and initiative...
2  Personalised blueprint of chronic inflammation...
3  CEPI 4 - Contribution to the Coalition for Epi...
4                                       Women TechEU
5                                       Women TechEU
6  Promoting implementation of research results i...
7       Strengthening ethics and regulatory capacity
8                                       Women TechEU
9                                       Women TechEU

                                       title_project
0  A point-of-care serological rapid diagnostic t...
1  Boosting innovation agencies for bioeconomy va...
2  GLYCANS AS MASTER TRIGGERS OF HEALTH TO INTEST...
3  Late-stage clinical development of Chikungunya...
4  The Oater develops a compact machine for hyper...
5  A System for the Early Diagnosis of Skeletal O...
6  EPiTB: Addressing an unmet need: same day diag...
7  Côte d'Ivoire Ethics Capacity Building Initiat...
8  Producing Green Hydrogen Using Power of Ocean ...
9        Elia - Smart Assistant for English Learning

In [32]:
# acronym
columns_to_compare_acronym = [
    'acronym', 
    'projectAcronym_x', 
    'projectAcronym_y', 
    'acronym_project', 
] 

print(merged_all[columns_to_compare_acronym].head(10)) #drop: projectAcronym_x, projectAcronym_y, acronmy_project

         acronym                                   projectAcronym_x  \
0      PvSeroRDT  PvSeroRDT; PvSeroRDT; PvSeroRDT; PvSeroRDT; Pv...
1       BIOBoost  BIOBoost; BIOBoost; BIOBoost; BIOBoost; BIOBoo...
2  GlycanTrigger  GlycanTrigger; GlycanTrigger; GlycanTrigger; G...
3   CHIKVAX_CHIM                                       CHIKVAX_CHIM
4      The Oater                                          The Oater
5    orthomobile                                        orthomobile
6          EPiTB                         EPiTB; EPiTB; EPiTB; EPiTB
7      CECABI II  CECABI II; CECABI II; CECABI II; CECABI II; CE...
8    GreenH2Wave                                        GreenH2Wave
9           ELIA                                               ELIA

                                    projectAcronym_y acronym_project
0                                                NaN       PvSeroRDT
1                                                NaN        BIOBoost
2  GlycanTrigger; GlycanTrigger; GlycanTrigger; G...   GlycanTrigger
3                                                NaN    CHIKVAX_CHIM
4                                                NaN       The Oater
5                                        orthomobile     orthomobile
6                                                NaN           EPiTB
7                                                NaN       CECABI II
8                                                NaN     GreenH2Wave
9                                                NaN            ELIA

In [33]:
# status
(merged_all['status'] == merged_all['status_project']).all() #drop: status_project

True

In [34]:
# total cost
columns_to_compare_totalCost = [
    'totalCost_x', 
    'totalCost_y', 
    'totalCost'
] 

print(merged_all[columns_to_compare_totalCost].head(10)) #drop: totalCost_x

  totalCost_x                                        totalCost_y   totalCost
0  4062396,23      0; 1777625; 272174,38; 0; 0; 2012596,85; 0; 0  4062396,23
1           0                             0; 0; 0; 0; 0; 0; 0; 0           0
2     6771571  893750; 0; 3478500; 188750; 766343,5; 0; 11275...     6771571
3   100000000                                          100000000   100000000
4           0                                                  0           0
5           0                                                  0           0
6  3989909,25        2618391,15; 388318,95; 461924,16; 521274,99  3989909,25
7     1000000                487000; 68000; 350000; 35000; 60000     1000000
8           0                                                  0           0
9           0                                                  0           0

In [35]:
(merged_all['totalCost_x'] == merged_all['totalCost']).all() #drop: status_project

True

In [36]:
# ecMaxContribution
(merged_all['ecMaxContribution'] == merged_all['ecMaxContribution_project']).all() #drop: ecMaxContribution_project

True

In [37]:
# total cost
columns_to_compare_legalBasis = [
    'legalBasis_x', 
    'legalBasis_y', 
    'legalBasis'
] 

print(merged_all[columns_to_compare_legalBasis].head(10)) #drop: legalBasis_x, legalBasis_y
(merged_all['legalBasis_x'] == merged_all['legalBasis']).all()

  legalBasis_x                legalBasis_y   legalBasis
0  HORIZON.2.1                 HORIZON.2.1  HORIZON.2.1
1  HORIZON.3.2  HORIZON.3.2; HORIZON.3.2.3  HORIZON.3.2
2  HORIZON.2.1  HORIZON.2.1; HORIZON.2.1.1  HORIZON.2.1
3  HORIZON.2.1  HORIZON.2.1; HORIZON.2.1.4  HORIZON.2.1
4  HORIZON.3.2                 HORIZON.3.2  HORIZON.3.2
5  HORIZON.3.2                 HORIZON.3.2  HORIZON.3.2
6  HORIZON.2.1                 HORIZON.2.1  HORIZON.2.1
7  HORIZON.2.1                 HORIZON.2.1  HORIZON.2.1
8  HORIZON.3.2                 HORIZON.3.2  HORIZON.3.2
9  HORIZON.3.2                 HORIZON.3.2  HORIZON.3.2

True

In [38]:
# topic
columns_to_compare_topic = [
    'topics', 
    'topic', 
    'topics_project'
] 

print(merged_all[columns_to_compare_topic].head(10)) #drop: topics, topics_project
(merged_all['topic'] == merged_all['topics_project']).all() 
(merged_all['topic'] == merged_all['topics']).all()

                                      topics  \
0  HORIZON-JU-GH-EDCTP3-2023-02-02-two-stage
1             HORIZON-EIE-2022-CONNECT-01-01
2           HORIZON-HLTH-2022-STAYHLTH-02-01
3           HORIZON-HLTH-2022-CEPI-15-01-IBA
4             HORIZON-EIE-2022-SCALEUP-02-02
5             HORIZON-EIE-2022-SCALEUP-02-02
6      HORIZON-JU-GH-EDCTP3-2022-CALL1-01-01
7            HORIZON-JU-GH-EDCTP3-2023-01-05
8             HORIZON-EIE-2022-SCALEUP-02-02
9             HORIZON-EIE-2022-SCALEUP-02-02

                                       topic  \
0  HORIZON-JU-GH-EDCTP3-2023-02-02-two-stage
1             HORIZON-EIE-2022-CONNECT-01-01
2           HORIZON-HLTH-2022-STAYHLTH-02-01
3           HORIZON-HLTH-2022-CEPI-15-01-IBA
4             HORIZON-EIE-2022-SCALEUP-02-02
5             HORIZON-EIE-2022-SCALEUP-02-02
6      HORIZON-JU-GH-EDCTP3-2022-CALL1-01-01
7            HORIZON-JU-GH-EDCTP3-2023-01-05
8             HORIZON-EIE-2022-SCALEUP-02-02
9             HORIZON-EIE-2022-SCALEUP-02-02

                              topics_project
0  HORIZON-JU-GH-EDCTP3-2023-02-02-two-stage
1             HORIZON-EIE-2022-CONNECT-01-01
2           HORIZON-HLTH-2022-STAYHLTH-02-01
3           HORIZON-HLTH-2022-CEPI-15-01-IBA
4             HORIZON-EIE-2022-SCALEUP-02-02
5             HORIZON-EIE-2022-SCALEUP-02-02
6      HORIZON-JU-GH-EDCTP3-2022-CALL1-01-01
7            HORIZON-JU-GH-EDCTP3-2023-01-05
8             HORIZON-EIE-2022-SCALEUP-02-02
9             HORIZON-EIE-2022-SCALEUP-02-02

True

In [39]:
# startDate
(merged_all['startDate'] == merged_all['startDate_project']).all() # TRUE, drop: startDate_project

True

In [40]:
# endDate
(merged_all['endDate'] == merged_all['endDate_project']).all() # TRUE: drop: endDate_project

True

In [41]:
# frameworkProgramme
(merged_all['frameworkProgramme'] == merged_all['frameworkProgramme_project']).all() # TRUE: drop: frameworkProgramme_project

True

In [42]:
# masterCall
(merged_all['masterCall'] == merged_all['masterCall_project']).all() # TRUE: drop: masterCall_project
print(merged_all['masterCall'].head(10))

0    HORIZON-JU-GH-EDCTP3-2023-02-two-stage
1               HORIZON-EIE-2022-CONNECT-01
2             HORIZON-HLTH-2022-STAYHLTH-02
3             HORIZON-HLTH-2022-CEPI-15-IBA
4               HORIZON-EIE-2022-SCALEUP-02
5               HORIZON-EIE-2022-SCALEUP-02
6              HORIZON-JU-GH-EDCTP3-2022-01
7              HORIZON-JU-GH-EDCTP3-2023-01
8               HORIZON-EIE-2022-SCALEUP-02
9               HORIZON-EIE-2022-SCALEUP-02
Name: masterCall, dtype: object

In [43]:
# subCall
(merged_all['subCall'] == merged_all['subCall_project']).all() # TRUE: drop: subCall_project
print(merged_all['masterCall'].head(10))
(merged_all['subCall'] == merged_all['masterCall']).all() # TRUE: drop: subCall

0    HORIZON-JU-GH-EDCTP3-2023-02-two-stage
1               HORIZON-EIE-2022-CONNECT-01
2             HORIZON-HLTH-2022-STAYHLTH-02
3             HORIZON-HLTH-2022-CEPI-15-IBA
4               HORIZON-EIE-2022-SCALEUP-02
5               HORIZON-EIE-2022-SCALEUP-02
6              HORIZON-JU-GH-EDCTP3-2022-01
7              HORIZON-JU-GH-EDCTP3-2023-01
8               HORIZON-EIE-2022-SCALEUP-02
9               HORIZON-EIE-2022-SCALEUP-02
Name: masterCall, dtype: object

True

In [44]:
# fundingScheme
(merged_all['fundingScheme'] == merged_all['fundingScheme_project']).all() # TRUE: drop: fundingScheme_project
print(merged_all['fundingScheme'].head(10))

0    HORIZON-JU-RIA
1       HORIZON-CSA
2       HORIZON-RIA
3    HORIZON-COFUND
4       HORIZON-CSA
5       HORIZON-CSA
6    HORIZON-JU-RIA
7    HORIZON-JU-CSA
8       HORIZON-CSA
9       HORIZON-CSA
Name: fundingScheme, dtype: object

In [45]:
# objective
(merged_all['objective'] == merged_all['objective_project']).all() # TRUE: drop: objective_project
print(merged_all['objective'].head(10))

0    Plasmodium vivax is considered the most diffic...
1    The overall objectives of the BIOBoost project...
2    Chronic inflammation underlies several disease...
3    A Framework Partnership Agreement (FPA) betwee...
4    The Oater is a female-founded food tech start-...
5    Orthodontics can correct deformities in the ma...
6    Better diagnostic approaches are required to i...
7    The number of studies and experiments on human...
8    The main objective of this project proposal is...
9    "We are a startup founded exclusively by women...
Name: objective, dtype: object

In [46]:
(merged_all['ecSignatureDate'] == merged_all['ecSignatureDate_project']).all() # TRUE: drop: objective_project

print(merged_all['ecSignatureDate'].head(10))
print(merged_all['ecSignatureDate_project'].head(10))
(merged_all['ecSignatureDate'] != merged_all['ecSignatureDate_project']).sum()

# This returns True only when values are different, treating NaNs as equal
mismatched_rows = merged_all[~(merged_all['ecSignatureDate'] == merged_all['ecSignatureDate_project']) & ~(merged_all['ecSignatureDate'].isna() & merged_all['ecSignatureDate_project'].isna())]

# Print only the mismatched rows
print(mismatched_rows[['ecSignatureDate', 'ecSignatureDate']]) # identical variables > drop: ecSignatureDate_project

0    2024-12-09
1    2022-11-25
2    2022-12-05
3    2023-06-15
4    2023-06-05
5    2023-07-30
6    2023-04-25
7    2024-07-15
8    2023-05-31
9    2023-06-05
Name: ecSignatureDate, dtype: object
0    2024-12-09
1    2022-11-25
2    2022-12-05
3    2023-06-15
4    2023-06-05
5    2023-07-30
6    2023-04-25
7    2024-07-15
8    2023-05-31
9    2023-06-05
Name: ecSignatureDate_project, dtype: object
Empty DataFrame
Columns: [ecSignatureDate, ecSignatureDate]
Index: []

In [47]:
(merged_all['fundingScheme'] == merged_all['fundingScheme_project']).all() # TRUE: drop: fundingScheme_project

True

In [48]:
# grantDoi
(merged_all['grantDoi'] == merged_all['grantDoi_project']).all() # TRUE: drop: objective_project
print(merged_all['grantDoi'].head(10))
print(merged_all['grantDoi_project'].head(10))
(merged_all['grantDoi'] != merged_all['grantDoi_project']).sum()

# This returns True only when values are different, treating NaNs as equal
mismatched_rows = merged_all[~(merged_all['grantDoi'] == merged_all['grantDoi_project']) & ~(merged_all['grantDoi'].isna() & merged_all['grantDoi_project'].isna())]

# Print only the mismatched rows
print(mismatched_rows[['grantDoi', 'grantDoi_project']]) # identical variables > drop: grantDoi_project

0    10.3030/101159220
1    10.3030/101096150
2    10.3030/101093997
3    10.3030/101126531
4    10.3030/101113979
5    10.3030/101113949
6    10.3030/101103281
7    10.3030/101145732
8    10.3030/101113993
9    10.3030/101114248
Name: grantDoi, dtype: object
0    10.3030/101159220
1    10.3030/101096150
2    10.3030/101093997
3    10.3030/101126531
4    10.3030/101113979
5    10.3030/101113949
6    10.3030/101103281
7    10.3030/101145732
8    10.3030/101113993
9    10.3030/101114248
Name: grantDoi_project, dtype: object
Empty DataFrame
Columns: [grantDoi, grantDoi_project]
Index: []

In [49]:
print(merged_all.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15863 entries, 0 to 15862
Data columns (total 83 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   projectID                   15863 non-null  int64
 1   acronym                     15863 non-null  object
 2   status                      15863 non-null  object
 3   title_x                     15863 non-null  object
 4   startDate                   15863 non-null  object
 5   endDate                     15863 non-null  object
 6   totalCost_x                 15863 non-null  object
 7   ecMaxContribution           15863 non-null  object
 8   legalBasis_x                15863 non-null  object
 9   topics                      15863 non-null  object
 10  ecSignatureDate             15862 non-null  object
 11  frameworkProgramme          15863 non-null  object
 12  masterCall                  15863 non-null  object
 13  subCall                     15863 non-null  object
 14  fundingScheme               15863 non-null  object
 15  nature                      0 non-null      float64
 16  objective                   15863 non-null  object
 17  contentUpdateDate_x         15863 non-null  object
 18  rcn_x                       15863 non-null  int64
 19  grantDoi                    15802 non-null  object
 20  projectAcronym_x            15863 non-null  object
 21  organisationID              15863 non-null  object
 22  vatNumber                   15863 non-null  object
 23  name                        15863 non-null  object
 24  shortName                   15863 non-null  object
 25  SME                         15863 non-null  object
 26  activityType                15863 non-null  object
 27  street                      15863 non-null  object
 28  postCode                    15863 non-null  object
 29  city                        15863 non-null  object
 30  country                     15863 non-null  object
 31  nutsCode                    15863 non-null  object
 32  geolocation                 15863 non-null  object
 33  organizationURL             15863 non-null  object
 34  contactForm                 15863 non-null  object
 35  contentUpdateDate_y         15863 non-null  object
 36  rcn_y                       15863 non-null  object
 37  order                       15863 non-null  object
 38  role                        15863 non-null  object
 39  ecContribution              15863 non-null  object
 40  netEcContribution           15863 non-null  object
 41  totalCost_y                 15863 non-null  object
 42  endOfParticipation          15863 non-null  object
 43  active                      15863 non-null  object
 44  legalBasis_y                15863 non-null  object
 45  title_y                     15863 non-null  object
 46  uniqueProgrammePart         15863 non-null  object
 47  id                          3969 non-null   object
 48  title                       3969 non-null   object
 49  isPublishedAs               3969 non-null   object
 50  authors                     3969 non-null   object
 51  journalTitle                3969 non-null   object
 52  journalNumber               3969 non-null   object
 53  publishedYear               3969 non-null   object
 54  publishedPages              3969 non-null   object
 55  issn                        3969 non-null   object
 56  isbn                        3969 non-null   object
 57  doi                         3969 non-null   object
 58  projectAcronym_y            3969 non-null   object
 59  collection                  3969 non-null   object
 60  contentUpdateDate           3969 non-null   object
 61  rcn                         3969 non-null   object
 62  topic                       15863 non-null  object
 63  title_topics                15863 non-null  object
 64  acronym_project             15863 non-null  object
 65  status_project              15863 non-null  object
 66  title_project               15863 non-null  object
 67  startDate_project           15863 non-null  object
 68  endDate_project             15863 non-null  object
 69  totalCost                   15863 non-null  object
 70  ecMaxContribution_project   15863 non-null  object
 71  legalBasis                  15863 non-null  object
 72  topics_project              15863 non-null  object
 73  ecSignatureDate_project     15862 non-null  object
 74  frameworkProgramme_project  15863 non-null  object
 75  masterCall_project          15863 non-null  object
 76  subCall_project             15863 non-null  object
 77  fundingScheme_project       15863 non-null  object
 78  nature_project              0 non-null      float64
 79  objective_project           15863 non-null  object
 80  contentUpdateDate_project   15863 non-null  object
 81  rcn_project                 15863 non-null  int64
 82  grantDoi_project            15802 non-null  object
dtypes: float64(2), int64(3), object(78)
memory usage: 10.0+ MB
None

DROP DUPLICATED COLUMNS

In [51]:
columns_to_drop1 = [ 
    'title',
	'title_y',
	'title_topics',
	'title_project',
	'projectAcronym_x', 
	'projectAcronym_y',
	'acronym_project',
	'status_project',
	'totalCost_x', 	
	'ecMaxContribution_project',
	'legalBasis_x',
	'legalBasis_y',
	'topics',
	'topics_project',
	'contentUpdateDate',
	'contentUpdateDate_x',
	'contentUpdateDate_y', 
	'contentUpdateDate_project',
	'rcn',
	'rcn_x',
	'rcn_y',
	'rcn_project',
	'startDate_project',
	'endDate_project',
	'frameworkProgramme_project',
	'masterCall_project',
	'subCall',
	'subCall_project',
	'fundingScheme_project',
    'objective_project',
    'ecSignatureDate_project',
	'grantDoi_project',
	'nature_project', 
	'nature',
]

df_minusDuplicates = merged_all.drop(columns=columns_to_drop1, errors='ignore')
print(df_minusDuplicates.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15863 entries, 0 to 15862
Data columns (total 49 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   projectID            15863 non-null  int64
 1   acronym              15863 non-null  object
 2   status               15863 non-null  object
 3   title_x              15863 non-null  object
 4   startDate            15863 non-null  object
 5   endDate              15863 non-null  object
 6   ecMaxContribution    15863 non-null  object
 7   ecSignatureDate      15862 non-null  object
 8   frameworkProgramme   15863 non-null  object
 9   masterCall           15863 non-null  object
 10  fundingScheme        15863 non-null  object
 11  objective            15863 non-null  object
 12  grantDoi             15802 non-null  object
 13  organisationID       15863 non-null  object
 14  vatNumber            15863 non-null  object
 15  name                 15863 non-null  object
 16  shortName            15863 non-null  object
 17  SME                  15863 non-null  object
 18  activityType         15863 non-null  object
 19  street               15863 non-null  object
 20  postCode             15863 non-null  object
 21  city                 15863 non-null  object
 22  country              15863 non-null  object
 23  nutsCode             15863 non-null  object
 24  geolocation          15863 non-null  object
 25  organizationURL      15863 non-null  object
 26  contactForm          15863 non-null  object
 27  order                15863 non-null  object
 28  role                 15863 non-null  object
 29  ecContribution       15863 non-null  object
 30  netEcContribution    15863 non-null  object
 31  totalCost_y          15863 non-null  object
 32  endOfParticipation   15863 non-null  object
 33  active               15863 non-null  object
 34  uniqueProgrammePart  15863 non-null  object
 35  id                   3969 non-null   object
 36  isPublishedAs        3969 non-null   object
 37  authors              3969 non-null   object
 38  journalTitle         3969 non-null   object
 39  journalNumber        3969 non-null   object
 40  publishedYear        3969 non-null   object
 41  publishedPages       3969 non-null   object
 42  issn                 3969 non-null   object
 43  isbn                 3969 non-null   object
 44  doi                  3969 non-null   object
 45  collection           3969 non-null   object
 46  topic                15863 non-null  object
 47  totalCost            15863 non-null  object
 48  legalBasis           15863 non-null  object
dtypes: int64(1), object(48)
memory usage: 5.9+ MB
None

In [52]:
print(df_minusDuplicates['SME'].head(10))
df_minusDuplicates['SME'].isna().sum() #keep SME

print(df_minusDuplicates['order'].head(10))
df_minusDuplicates['order'].isna().sum() # drop order

print(df_minusDuplicates['role'].head(10))
df_minusDuplicates['role'].isna().sum() # keep role 

print(df_minusDuplicates['endOfParticipation'].head(10))
df_minusDuplicates['endOfParticipation'].isna().sum() # keep endOfParticipation

print(df_minusDuplicates['active'].head(10))
df_minusDuplicates['active'].isna().sum() # drop active

print(df_minusDuplicates['totalCost_y'].head(10))
df_minusDuplicates['totalCost_y'].isna().sum()

print(df_minusDuplicates['collection'].head(10))
df_minusDuplicates['collection'].isna().sum() # drop collection

print(df_minusDuplicates['uniqueProgrammePart'].head(10))

0    False; False; False; False; False; False; True...
1    True; True; True; False; False; False; False; ...
2    False; True; False; True; False; False; False;...
3                                                False
4                                                 True
5                                                 True
6                           False; False; False; False
7                     False; False; True; False; False
8                                                 True
9                                                 True
Name: SME, dtype: object
0          4; 2; 3; 6; 7; 1; 5; 8
1          8; 1; 6; 5; 4; 3; 2; 7
2    2; 9; 1; 8; 5; 5; 7; 4; 6; 3
3                               1
4                               1
5                               1
6                      1; 2; 4; 3
7                   5; 4; 1; 2; 3
8                               1
9                               1
Name: order, dtype: object
0    associatedPartner; participant; participant; a...
1    participant; coordinator; participant; partici...
2    participant; associatedPartner; coordinator; p...
3                                          coordinator
4                                          coordinator
5                                          coordinator
6    coordinator; participant; participant; partici...
7    participant; participant; coordinator; partici...
8                                          coordinator
9                                          coordinator
Name: role, dtype: object
0    False; False; False; False; False; False; Fals...
1    False; False; False; False; False; False; Fals...
2    False; False; False; False; False; False; Fals...
3                                                False
4                                                False
5                                                False
6                           False; False; False; False
7                    False; False; False; False; False
8                                                False
9                                                False
Name: endOfParticipation, dtype: object
0
1
2
3
4
5
6
7
8
9
Name: active, dtype: object
0        0; 1777625; 272174,38; 0; 0; 2012596,85; 0; 0
1                               0; 0; 0; 0; 0; 0; 0; 0
2    893750; 0; 3478500; 188750; 766343,5; 0; 11275...
3                                            100000000
4                                                    0
5                                                    0
6          2618391,15; 388318,95; 461924,16; 521274,99
7                  487000; 68000; 350000; 35000; 60000
8                                                    0
9                                                    0
Name: totalCost_y, dtype: object
0                                                  NaN
1                                                  NaN
2    Project publication; Project publication; Proj...
3                                                  NaN
4                                                  NaN
5                                  Project publication
6                                                  NaN
7                                                  NaN
8                                                  NaN
9                                                  NaN
Name: collection, dtype: object
0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
8    True
9    True
Name: uniqueProgrammePart, dtype: object

In [53]:
print(df_minusDuplicates.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15863 entries, 0 to 15862
Data columns (total 49 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   projectID            15863 non-null  int64
 1   acronym              15863 non-null  object
 2   status               15863 non-null  object
 3   title_x              15863 non-null  object
 4   startDate            15863 non-null  object
 5   endDate              15863 non-null  object
 6   ecMaxContribution    15863 non-null  object
 7   ecSignatureDate      15862 non-null  object
 8   frameworkProgramme   15863 non-null  object
 9   masterCall           15863 non-null  object
 10  fundingScheme        15863 non-null  object
 11  objective            15863 non-null  object
 12  grantDoi             15802 non-null  object
 13  organisationID       15863 non-null  object
 14  vatNumber            15863 non-null  object
 15  name                 15863 non-null  object
 16  shortName            15863 non-null  object
 17  SME                  15863 non-null  object
 18  activityType         15863 non-null  object
 19  street               15863 non-null  object
 20  postCode             15863 non-null  object
 21  city                 15863 non-null  object
 22  country              15863 non-null  object
 23  nutsCode             15863 non-null  object
 24  geolocation          15863 non-null  object
 25  organizationURL      15863 non-null  object
 26  contactForm          15863 non-null  object
 27  order                15863 non-null  object
 28  role                 15863 non-null  object
 29  ecContribution       15863 non-null  object
 30  netEcContribution    15863 non-null  object
 31  totalCost_y          15863 non-null  object
 32  endOfParticipation   15863 non-null  object
 33  active               15863 non-null  object
 34  uniqueProgrammePart  15863 non-null  object
 35  id                   3969 non-null   object
 36  isPublishedAs        3969 non-null   object
 37  authors              3969 non-null   object
 38  journalTitle         3969 non-null   object
 39  journalNumber        3969 non-null   object
 40  publishedYear        3969 non-null   object
 41  publishedPages       3969 non-null   object
 42  issn                 3969 non-null   object
 43  isbn                 3969 non-null   object
 44  doi                  3969 non-null   object
 45  collection           3969 non-null   object
 46  topic                15863 non-null  object
 47  totalCost            15863 non-null  object
 48  legalBasis           15863 non-null  object
dtypes: int64(1), object(48)
memory usage: 5.9+ MB
None

In [54]:
(df_minusDuplicates['totalCost_y'] == df_minusDuplicates['totalCost']).all()

# This returns True only when values are different, treating NaNs as equal
mismatched_rows = df_minusDuplicates[~(df_minusDuplicates['totalCost'] == df_minusDuplicates['totalCost_y']) & ~(df_minusDuplicates['totalCost'].isna() & df_minusDuplicates['totalCost_y'].isna())]

# Print only the mismatched rows
print(mismatched_rows[['totalCost', 'totalCost_y']]) 

df_minusDuplicates['totalCost_y'].isna().sum() # drop totalCost_y
df_minusDuplicates['totalCost'].isna().sum() # drop

        totalCost                                        totalCost_y
0      4062396,23      0; 1777625; 272174,38; 0; 0; 2012596,85; 0; 0
1               0                             0; 0; 0; 0; 0; 0; 0; 0
2         6771571  893750; 0; 3478500; 188750; 766343,5; 0; 11275...
6      3989909,25        2618391,15; 388318,95; 461924,16; 521274,99
7         1000000                487000; 68000; 350000; 35000; 60000
...           ...                                                ...
15851           0                                0; 0; 0; 0; 0; 0; 0
15852           0                                         0; 0; 0; 0
15853           0                                0; 0; 0; 0; 0; 0; 0
15854  4998778,75  418702,5; 306003,75; 685213,75; 0; 274635; 519...
15862     1046625                     196250; 355750; 259000; 235625

[8458 rows x 2 columns]

0

In [55]:
columns_to_drop2 = [ 
    'vatNumber',
    'shortName', 
    'street', 
    'nutsCode',
    'postCode', 
    'geolocation',
    'nutscode', 
    'contactForm', 
    'id', 
    'journalNumber', 
    'publishedPages', 
    'authors', 
    'issn', 
    'isbn',
    'order', 
    'uniqueProgrammePart',
    'active', 
    'collection', 
    'organizationURL',
    'frameworkProgramme', 
    'isPublishedAs',
    'endOfParticipation',
    'journalTitle', 
    'doi', 
    'publishedYear', 
    'activityType', 
    'totalCost_y',
    
]

df_minusUnnecessaryVar = df_minusDuplicates.drop(columns=columns_to_drop2, errors='ignore')
print(df_minusUnnecessaryVar.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15863 entries, 0 to 15862
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   projectID          15863 non-null  int64
 1   acronym            15863 non-null  object
 2   status             15863 non-null  object
 3   title_x            15863 non-null  object
 4   startDate          15863 non-null  object
 5   endDate            15863 non-null  object
 6   ecMaxContribution  15863 non-null  object
 7   ecSignatureDate    15862 non-null  object
 8   masterCall         15863 non-null  object
 9   fundingScheme      15863 non-null  object
 10  objective          15863 non-null  object
 11  grantDoi           15802 non-null  object
 12  organisationID     15863 non-null  object
 13  name               15863 non-null  object
 14  SME                15863 non-null  object
 15  city               15863 non-null  object
 16  country            15863 non-null  object
 17  role               15863 non-null  object
 18  ecContribution     15863 non-null  object
 19  netEcContribution  15863 non-null  object
 20  topic              15863 non-null  object
 21  totalCost          15863 non-null  object
 22  legalBasis         15863 non-null  object
dtypes: int64(1), object(22)
memory usage: 2.8+ MB
None

STEP: CHECK DATATYPES

In [57]:
print(df_minusUnnecessaryVar.head(5))

   projectID        acronym  status  \
0  101159220      PvSeroRDT  SIGNED
1  101096150       BIOBoost  SIGNED
2  101093997  GlycanTrigger  SIGNED
3  101126531   CHIKVAX_CHIM  SIGNED
4  101113979      The Oater  CLOSED

                                             title_x   startDate     endDate  \
0  A point-of-care serological rapid diagnostic t...  2025-02-01  2030-01-31
1  Boosting innovation agencies for bioeconomy va...  2023-02-01  2025-01-31
2  GLYCANS AS MASTER TRIGGERS OF HEALTH TO INTEST...  2023-01-01  2028-12-31
3  Late-stage clinical development of Chikungunya...  2023-06-01  2028-11-30
4  The Oater develops a compact machine for hyper...  2023-07-01  2023-12-31

  ecMaxContribution ecSignatureDate                              masterCall  \
0        4062396,23      2024-12-09  HORIZON-JU-GH-EDCTP3-2023-02-two-stage
1            500000      2022-11-25             HORIZON-EIE-2022-CONNECT-01
2           6771571      2022-12-05           HORIZON-HLTH-2022-STAYHLTH-02
3          70000000      2023-06-15           HORIZON-HLTH-2022-CEPI-15-IBA
4             75000      2023-06-05             HORIZON-EIE-2022-SCALEUP-02

    fundingScheme  ...                                               name  \
0  HORIZON-JU-RIA  ...  Institut Pasteur de Madagascar; INSTITUT PASTE...
1     HORIZON-CSA  ...  CLIC INNOVATION OY; FBCD AS; BIOECONOMY FOR CH...
2     HORIZON-RIA  ...  ACADEMISCH ZIEKENHUIS LEIDEN; LUDGER LIMITED; ...
3  HORIZON-COFUND  ...    COALITION FOR EPIDEMIC PREPAREDNESS INNOVATIONS
4     HORIZON-CSA  ...                                 OIY SOLUTIONS GMBH

                                                 SME  \
0  False; False; False; False; False; False; True...
1  True; True; True; False; False; False; False; ...
2  False; True; False; True; False; False; False;...
3                                              False
4                                               True

                                                city  \
0  Antananarivo; Dakar; Addis Ababa; London; Gene...
1  Helsinki; Tjele; Barenton Bugny; Granada; Murs...
2  Leiden; Abingdon; Porto; Porto; Lisboa; Lisboa...
3                                               Oslo
4                                             Aachen

                                  country  \
0          MG; SN; ET; UK; CH; FR; UK; AU
1          FI; DK; FR; ES; SI; LT; PL; PL
2  NL; UK; PT; PT; PT; PT; BE; DE; US; FR
3                                      NO
4                                      DE

                                                role  \
0  associatedPartner; participant; participant; a...
1  participant; coordinator; participant; partici...
2  participant; associatedPartner; coordinator; p...
3                                        coordinator
4                                        coordinator

                                      ecContribution  \
0                   1777625.0; 272174.38; 2012596.85
1  68562.5; 91812.5; 65937.5; 42562.5; 60625.0; 5...
2  893750.0; 3478500.0; 188750.0; 766343.5; 0.0; ...
3                                         70000000.0
4                                            75000.0

                                   netEcContribution  \
0  0.0; 1777625.0; 272174.38; 0.0; 0.0; 2012596.8...
1  68562.5; 91812.5; 65937.5; 42562.5; 60625.0; 5...
2  893750.0; 0.0; 3478500.0; 188750.0; 473968.5; ...
3                                         70000000.0
4                                            75000.0

                                       topic   totalCost   legalBasis
0  HORIZON-JU-GH-EDCTP3-2023-02-02-two-stage  4062396,23  HORIZON.2.1
1             HORIZON-EIE-2022-CONNECT-01-01           0  HORIZON.3.2
2           HORIZON-HLTH-2022-STAYHLTH-02-01     6771571  HORIZON.2.1
3           HORIZON-HLTH-2022-CEPI-15-01-IBA   100000000  HORIZON.2.1
4             HORIZON-EIE-2022-SCALEUP-02-02           0  HORIZON.3.2

[5 rows x 23 columns]

In [58]:
# Convert financial columns: replace comma with dot, then to numeric
for col in ['ecMaxContribution', 'totalCost']:
    df_minusUnnecessaryVar[col] = pd.to_numeric(
        df_minusUnnecessaryVar[col].astype(str).str.replace(',', '.', regex=False),
        errors='coerce'
    )
# Convert date columns to datetime
date_cols = ['startDate', 'endDate', 'ecSignatureDate']
for col in date_cols:
    df_minusUnnecessaryVar[col] = pd.to_datetime(df_minusUnnecessaryVar[col], errors='coerce')

# Convert publishedYear to string (safe if it contains semicolon-separated values)
if 'publishedYear' in df_minusUnnecessaryVar.columns:
    df_minusUnnecessaryVar['publishedYear'] = df_minusUnnecessaryVar['publishedYear'].astype(str)

# Check the updated data types
print(df_minusUnnecessaryVar.dtypes)

projectID                     int64
acronym                      object
status                       object
title_x                      object
startDate            datetime64[ns]
endDate              datetime64[ns]
ecMaxContribution           float64
ecSignatureDate      datetime64[ns]
masterCall                   object
fundingScheme                object
objective                    object
grantDoi                     object
organisationID               object
name                         object
SME                          object
city                         object
country                      object
role                         object
ecContribution               object
netEcContribution            object
topic                        object
totalCost                   float64
legalBasis                   object
dtype: object

In [59]:
# rename title_x to title
df_minusUnnecessaryVar.rename(columns={'title_x': 'title'}, inplace=True)
print(df_minusUnnecessaryVar.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15863 entries, 0 to 15862
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   projectID          15863 non-null  int64
 1   acronym            15863 non-null  object
 2   status             15863 non-null  object
 3   title              15863 non-null  object
 4   startDate          15863 non-null  datetime64[ns]
 5   endDate            15863 non-null  datetime64[ns]
 6   ecMaxContribution  15863 non-null  float64
 7   ecSignatureDate    15862 non-null  datetime64[ns]
 8   masterCall         15863 non-null  object
 9   fundingScheme      15863 non-null  object
 10  objective          15863 non-null  object
 11  grantDoi           15802 non-null  object
 12  organisationID     15863 non-null  object
 13  name               15863 non-null  object
 14  SME                15863 non-null  object
 15  city               15863 non-null  object
 16  country            15863 non-null  object
 17  role               15863 non-null  object
 18  ecContribution     15863 non-null  object
 19  netEcContribution  15863 non-null  object
 20  topic              15863 non-null  object
 21  totalCost          15863 non-null  float64
 22  legalBasis         15863 non-null  object
dtypes: datetime64[ns](3), float64(2), int64(1), object(17)
memory usage: 2.8+ MB
None

In [60]:
print(df_minusUnnecessaryVar['ecMaxContribution'].head(10))
print(df_minusUnnecessaryVar['ecContribution'].head(10))
print(df_minusUnnecessaryVar['netEcContribution'].head(10))
print(df_minusUnnecessaryVar['totalCost'].head(10))

0     4062396.23
1      500000.00
2     6771571.00
3    70000000.00
4       75000.00
5       75000.00
6     3989909.25
7     1000000.00
8       75000.00
9       75000.00
Name: ecMaxContribution, dtype: float64
0                     1777625.0; 272174.38; 2012596.85
1    68562.5; 91812.5; 65937.5; 42562.5; 60625.0; 5...
2    893750.0; 3478500.0; 188750.0; 766343.5; 0.0; ...
3                                           70000000.0
4                                              75000.0
5                                              75000.0
6          2618391.15; 388318.95; 461924.16; 521274.99
7        487000.0; 68000.0; 350000.0; 35000.0; 60000.0
8                                              75000.0
9                                              75000.0
Name: ecContribution, dtype: object
0    0.0; 1777625.0; 272174.38; 0.0; 0.0; 2012596.8...
1    68562.5; 91812.5; 65937.5; 42562.5; 60625.0; 5...
2    893750.0; 0.0; 3478500.0; 188750.0; 473968.5; ...
3                                           70000000.0
4                                              75000.0
5                                              75000.0
6          2618391.15; 388318.95; 461924.16; 521274.99
7        487000.0; 68000.0; 350000.0; 35000.0; 60000.0
8                                              75000.0
9                                              75000.0
Name: netEcContribution, dtype: object
0    4.062396e+06
1    0.000000e+00
2    6.771571e+06
3    1.000000e+08
4    0.000000e+00
5    0.000000e+00
6    3.989909e+06
7    1.000000e+06
8    0.000000e+00
9    0.000000e+00
Name: totalCost, dtype: float64

In [61]:
# Define a function to safely split and sum semicolon-separated values
def sum_contributions(val):
    if pd.isna(val):
        return 0.0
    try:
        numbers = [float(x.strip()) for x in val.split(';') if x.strip()]
        return sum(numbers)
    except:
        return 0.0

# Apply it to ecContribution and netEcContribution
df_minusUnnecessaryVar['ecContribution_sum'] = df_minusUnnecessaryVar['ecContribution'].apply(sum_contributions)
df_minusUnnecessaryVar['netEcContribution_sum'] = df_minusUnnecessaryVar['netEcContribution'].apply(sum_contributions)

# Now compare with ecMaxContribution
df_minusUnnecessaryVar['ec_match'] = np.isclose(
    df_minusUnnecessaryVar['ecContribution_sum'], 
    df_minusUnnecessaryVar['ecMaxContribution'], 
    atol=1e-2
)

# View mismatches
mismatches = df_minusUnnecessaryVar[~df_minusUnnecessaryVar['ec_match']]
print(mismatches[['ecMaxContribution', 'ecContribution_sum']])

       ecMaxContribution  ecContribution_sum
50            6823071.25          6659571.25
51             599947.50           595068.61
234           9900000.00          9732567.71
666            209914.56           194074.56
991            763600.00           726800.00
...                  ...                 ...
15682         2834688.25          3186888.25
15727        14999509.00         14529561.02
15785         1847562.00          1772172.60
15790        22712147.00         20194083.00
15843          750000.00           897250.00

[189 rows x 2 columns]

In [62]:
print(df_minusUnnecessaryVar.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15863 entries, 0 to 15862
Data columns (total 26 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   projectID              15863 non-null  int64
 1   acronym                15863 non-null  object
 2   status                 15863 non-null  object
 3   title                  15863 non-null  object
 4   startDate              15863 non-null  datetime64[ns]
 5   endDate                15863 non-null  datetime64[ns]
 6   ecMaxContribution      15863 non-null  float64
 7   ecSignatureDate        15862 non-null  datetime64[ns]
 8   masterCall             15863 non-null  object
 9   fundingScheme          15863 non-null  object
 10  objective              15863 non-null  object
 11  grantDoi               15802 non-null  object
 12  organisationID         15863 non-null  object
 13  name                   15863 non-null  object
 14  SME                    15863 non-null  object
 15  city                   15863 non-null  object
 16  country                15863 non-null  object
 17  role                   15863 non-null  object
 18  ecContribution         15863 non-null  object
 19  netEcContribution      15863 non-null  object
 20  topic                  15863 non-null  object
 21  totalCost              15863 non-null  float64
 22  legalBasis             15863 non-null  object
 23  ecContribution_sum     15863 non-null  float64
 24  netEcContribution_sum  15863 non-null  float64
 25  ec_match               15863 non-null  bool
dtypes: bool(1), datetime64[ns](3), float64(4), int64(1), object(17)
memory usage: 3.0+ MB
None

In [63]:
print(df_minusUnnecessaryVar['status'].head(10))
print(df_minusUnnecessaryVar['masterCall'].head(10))
print(df_minusUnnecessaryVar['fundingScheme'].head(10))
print(df_minusUnnecessaryVar['role'].head(10))
print(df_minusUnnecessaryVar['topic'].head(10))

0    SIGNED
1    SIGNED
2    SIGNED
3    SIGNED
4    CLOSED
5    SIGNED
6    SIGNED
7    SIGNED
8    CLOSED
9    CLOSED
Name: status, dtype: object
0    HORIZON-JU-GH-EDCTP3-2023-02-two-stage
1               HORIZON-EIE-2022-CONNECT-01
2             HORIZON-HLTH-2022-STAYHLTH-02
3             HORIZON-HLTH-2022-CEPI-15-IBA
4               HORIZON-EIE-2022-SCALEUP-02
5               HORIZON-EIE-2022-SCALEUP-02
6              HORIZON-JU-GH-EDCTP3-2022-01
7              HORIZON-JU-GH-EDCTP3-2023-01
8               HORIZON-EIE-2022-SCALEUP-02
9               HORIZON-EIE-2022-SCALEUP-02
Name: masterCall, dtype: object
0    HORIZON-JU-RIA
1       HORIZON-CSA
2       HORIZON-RIA
3    HORIZON-COFUND
4       HORIZON-CSA
5       HORIZON-CSA
6    HORIZON-JU-RIA
7    HORIZON-JU-CSA
8       HORIZON-CSA
9       HORIZON-CSA
Name: fundingScheme, dtype: object
0    associatedPartner; participant; participant; a...
1    participant; coordinator; participant; partici...
2    participant; associatedPartner; coordinator; p...
3                                          coordinator
4                                          coordinator
5                                          coordinator
6    coordinator; participant; participant; partici...
7    participant; participant; coordinator; partici...
8                                          coordinator
9                                          coordinator
Name: role, dtype: object
0    HORIZON-JU-GH-EDCTP3-2023-02-02-two-stage
1               HORIZON-EIE-2022-CONNECT-01-01
2             HORIZON-HLTH-2022-STAYHLTH-02-01
3             HORIZON-HLTH-2022-CEPI-15-01-IBA
4               HORIZON-EIE-2022-SCALEUP-02-02
5               HORIZON-EIE-2022-SCALEUP-02-02
6        HORIZON-JU-GH-EDCTP3-2022-CALL1-01-01
7              HORIZON-JU-GH-EDCTP3-2023-01-05
8               HORIZON-EIE-2022-SCALEUP-02-02
9               HORIZON-EIE-2022-SCALEUP-02-02
Name: topic, dtype: object

In [64]:
columns_to_drop3 = [ 
    'ecContribution_sum', 
    'netEcContribution_sum', 
    'ec_match',   
]

df_mda = df_minusUnnecessaryVar.drop(columns=columns_to_drop3, errors='ignore')
print(df_mda.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15863 entries, 0 to 15862
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   projectID          15863 non-null  int64
 1   acronym            15863 non-null  object
 2   status             15863 non-null  object
 3   title              15863 non-null  object
 4   startDate          15863 non-null  datetime64[ns]
 5   endDate            15863 non-null  datetime64[ns]
 6   ecMaxContribution  15863 non-null  float64
 7   ecSignatureDate    15862 non-null  datetime64[ns]
 8   masterCall         15863 non-null  object
 9   fundingScheme      15863 non-null  object
 10  objective          15863 non-null  object
 11  grantDoi           15802 non-null  object
 12  organisationID     15863 non-null  object
 13  name               15863 non-null  object
 14  SME                15863 non-null  object
 15  city               15863 non-null  object
 16  country            15863 non-null  object
 17  role               15863 non-null  object
 18  ecContribution     15863 non-null  object
 19  netEcContribution  15863 non-null  object
 20  topic              15863 non-null  object
 21  totalCost          15863 non-null  float64
 22  legalBasis         15863 non-null  object
dtypes: datetime64[ns](3), float64(2), int64(1), object(17)
memory usage: 2.8+ MB
None

Data Exploration

In [66]:
# Missings per variable
df_mda.isnull().sum()

projectID             0
acronym               0
status                0
title                 0
startDate             0
endDate               0
ecMaxContribution     0
ecSignatureDate       1
masterCall            0
fundingScheme         0
objective             0
grantDoi             61
organisationID        0
name                  0
SME                   0
city                  0
country               0
role                  0
ecContribution        0
netEcContribution     0
topic                 0
totalCost             0
legalBasis            0
dtype: int64

In [67]:
print(df_mda.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15863 entries, 0 to 15862
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   projectID          15863 non-null  int64
 1   acronym            15863 non-null  object
 2   status             15863 non-null  object
 3   title              15863 non-null  object
 4   startDate          15863 non-null  datetime64[ns]
 5   endDate            15863 non-null  datetime64[ns]
 6   ecMaxContribution  15863 non-null  float64
 7   ecSignatureDate    15862 non-null  datetime64[ns]
 8   masterCall         15863 non-null  object
 9   fundingScheme      15863 non-null  object
 10  objective          15863 non-null  object
 11  grantDoi           15802 non-null  object
 12  organisationID     15863 non-null  object
 13  name               15863 non-null  object
 14  SME                15863 non-null  object
 15  city               15863 non-null  object
 16  country            15863 non-null  object
 17  role               15863 non-null  object
 18  ecContribution     15863 non-null  object
 19  netEcContribution  15863 non-null  object
 20  topic              15863 non-null  object
 21  totalCost          15863 non-null  float64
 22  legalBasis         15863 non-null  object
dtypes: datetime64[ns](3), float64(2), int64(1), object(17)
memory usage: 2.8+ MB
None

In [68]:
# Convert semicolon-separated strings to float (if needed)
df_mda['ecContribution_sum'] = df_mda['ecContribution'].str.split(';').apply(
    lambda x: sum([float(i.strip()) for i in x if i.strip()]) if isinstance(x, list) else None
)

df_mda['netEcContribution_sum'] = df_mda['netEcContribution'].str.split(';').apply(
    lambda x: sum([float(i.strip()) for i in x if i.strip()]) if isinstance(x, list) else None
)

# Convert to category
categorical_cols = ['fundingScheme', 'masterCall', 'topic', 'role', 'legalBasis', 'status']
df_mda[categorical_cols] = df_mda[categorical_cols].astype('category')

In [69]:
print(df_mda.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15863 entries, 0 to 15862
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   projectID              15863 non-null  int64
 1   acronym                15863 non-null  object
 2   status                 15863 non-null  category
 3   title                  15863 non-null  object
 4   startDate              15863 non-null  datetime64[ns]
 5   endDate                15863 non-null  datetime64[ns]
 6   ecMaxContribution      15863 non-null  float64
 7   ecSignatureDate        15862 non-null  datetime64[ns]
 8   masterCall             15863 non-null  category
 9   fundingScheme          15863 non-null  category
 10  objective              15863 non-null  object
 11  grantDoi               15802 non-null  object
 12  organisationID         15863 non-null  object
 13  name                   15863 non-null  object
 14  SME                    15863 non-null  object
 15  city                   15863 non-null  object
 16  country                15863 non-null  object
 17  role                   15863 non-null  category
 18  ecContribution         15863 non-null  object
 19  netEcContribution      15863 non-null  object
 20  topic                  15863 non-null  category
 21  totalCost              15863 non-null  float64
 22  legalBasis             15863 non-null  category
 23  ecContribution_sum     15863 non-null  float64
 24  netEcContribution_sum  15863 non-null  float64
dtypes: category(6), datetime64[ns](3), float64(4), int64(1), object(11)
memory usage: 2.7+ MB
None

In [70]:
df_mda['ecContribution_list'] = df_mda['ecContribution'].str.split(';').apply(
    lambda x: [float(i.strip()) for i in x if i.strip()]
)
df_mda['netEcContribution_list'] = df_mda['netEcContribution'].str.split(';').apply(
    lambda x: [float(i.strip()) for i in x if i.strip()]
)

In [71]:
print(df_mda.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15863 entries, 0 to 15862
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   projectID               15863 non-null  int64
 1   acronym                 15863 non-null  object
 2   status                  15863 non-null  category
 3   title                   15863 non-null  object
 4   startDate               15863 non-null  datetime64[ns]
 5   endDate                 15863 non-null  datetime64[ns]
 6   ecMaxContribution       15863 non-null  float64
 7   ecSignatureDate         15862 non-null  datetime64[ns]
 8   masterCall              15863 non-null  category
 9   fundingScheme           15863 non-null  category
 10  objective               15863 non-null  object
 11  grantDoi                15802 non-null  object
 12  organisationID          15863 non-null  object
 13  name                    15863 non-null  object
 14  SME                     15863 non-null  object
 15  city                    15863 non-null  object
 16  country                 15863 non-null  object
 17  role                    15863 non-null  category
 18  ecContribution          15863 non-null  object
 19  netEcContribution       15863 non-null  object
 20  topic                   15863 non-null  category
 21  totalCost               15863 non-null  float64
 22  legalBasis              15863 non-null  category
 23  ecContribution_sum      15863 non-null  float64
 24  netEcContribution_sum   15863 non-null  float64
 25  ecContribution_list     15863 non-null  object
 26  netEcContribution_list  15863 non-null  object
dtypes: category(6), datetime64[ns](3), float64(4), int64(1), object(13)
memory usage: 2.9+ MB
None

In [72]:
print(df_mda['ecContribution_list'].iloc[0])  # Should print a list like [68562.5, 91812.5, ...]

[1777625.0, 272174.38, 2012596.85]

In [73]:
df_mda['ecMaxContribution'].describe()

count    1.586300e+04
mean     2.795369e+06
std      8.180198e+06
min      4.659400e+04
25%      2.117549e+05
50%      1.700000e+06
75%      2.999314e+06
max      5.494420e+08
Name: ecMaxContribution, dtype: float64

In [128]:
print(df_mda.head(10))

   projectID        acronym  status  \
0  101159220      PvSeroRDT  SIGNED
1  101096150       BIOBoost  SIGNED
2  101093997  GlycanTrigger  SIGNED
3  101126531   CHIKVAX_CHIM  SIGNED
4  101113979      The Oater  CLOSED
5  101113949    orthomobile  SIGNED
6  101103281          EPiTB  SIGNED
7  101145732      CECABI II  SIGNED
8  101113993    GreenH2Wave  CLOSED
9  101114248           ELIA  CLOSED

                                               title  startDate    endDate  \
0  A point-of-care serological rapid diagnostic t... 2025-02-01 2030-01-31
1  Boosting innovation agencies for bioeconomy va... 2023-02-01 2025-01-31
2  GLYCANS AS MASTER TRIGGERS OF HEALTH TO INTEST... 2023-01-01 2028-12-31
3  Late-stage clinical development of Chikungunya... 2023-06-01 2028-11-30
4  The Oater develops a compact machine for hyper... 2023-07-01 2023-12-31
5  A System for the Early Diagnosis of Skeletal O... 2023-08-01 2024-07-31
6  EPiTB: Addressing an unmet need: same day diag... 2023-05-01 2026-04-30
7  Côte d'Ivoire Ethics Capacity Building Initiat... 2024-06-01 2027-05-31
8  Producing Green Hydrogen Using Power of Ocean ... 2023-08-01 2024-07-31
9        Elia - Smart Assistant for English Learning 2023-07-01 2024-06-30

   ecMaxContribution ecSignatureDate                              masterCall  \
0         4062396.23      2024-12-09  HORIZON-JU-GH-EDCTP3-2023-02-two-stage
1          500000.00      2022-11-25             HORIZON-EIE-2022-CONNECT-01
2         6771571.00      2022-12-05           HORIZON-HLTH-2022-STAYHLTH-02
3        70000000.00      2023-06-15           HORIZON-HLTH-2022-CEPI-15-IBA
4           75000.00      2023-06-05             HORIZON-EIE-2022-SCALEUP-02
5           75000.00      2023-07-30             HORIZON-EIE-2022-SCALEUP-02
6         3989909.25      2023-04-25            HORIZON-JU-GH-EDCTP3-2022-01
7         1000000.00      2024-07-15            HORIZON-JU-GH-EDCTP3-2023-01
8           75000.00      2023-05-31             HORIZON-EIE-2022-SCALEUP-02
9           75000.00      2023-06-05             HORIZON-EIE-2022-SCALEUP-02

    fundingScheme  ...                                               role  \
0  HORIZON-JU-RIA  ...  associatedPartner; participant; participant; a...
1     HORIZON-CSA  ...  participant; coordinator; participant; partici...
2     HORIZON-RIA  ...  participant; associatedPartner; coordinator; p...
3  HORIZON-COFUND  ...                                        coordinator
4     HORIZON-CSA  ...                                        coordinator
5     HORIZON-CSA  ...                                        coordinator
6  HORIZON-JU-RIA  ...  coordinator; participant; participant; partici...
7  HORIZON-JU-CSA  ...  participant; participant; coordinator; partici...
8     HORIZON-CSA  ...                                        coordinator
9     HORIZON-CSA  ...                                        coordinator

                                      ecContribution  \
0                   1777625.0; 272174.38; 2012596.85
1  68562.5; 91812.5; 65937.5; 42562.5; 60625.0; 5...
2  893750.0; 3478500.0; 188750.0; 766343.5; 0.0; ...
3                                         70000000.0
4                                            75000.0
5                                            75000.0
6        2618391.15; 388318.95; 461924.16; 521274.99
7      487000.0; 68000.0; 350000.0; 35000.0; 60000.0
8                                            75000.0
9                                            75000.0

                                   netEcContribution  \
0  0.0; 1777625.0; 272174.38; 0.0; 0.0; 2012596.8...
1  68562.5; 91812.5; 65937.5; 42562.5; 60625.0; 5...
2  893750.0; 0.0; 3478500.0; 188750.0; 473968.5; ...
3                                         70000000.0
4                                            75000.0
5                                            75000.0
6        2618391.15; 388318.95; 461924.16; 521274.99
7      487000.0; 68000.0; 350000.0; 35000.0; 60000.0
8                                            75000.0
9                                            75000.0

                                       topic     totalCost   legalBasis  \
0  HORIZON-JU-GH-EDCTP3-2023-02-02-two-stage  4.062396e+06  HORIZON.2.1
1             HORIZON-EIE-2022-CONNECT-01-01  0.000000e+00  HORIZON.3.2
2           HORIZON-HLTH-2022-STAYHLTH-02-01  6.771571e+06  HORIZON.2.1
3           HORIZON-HLTH-2022-CEPI-15-01-IBA  1.000000e+08  HORIZON.2.1
4             HORIZON-EIE-2022-SCALEUP-02-02  0.000000e+00  HORIZON.3.2
5             HORIZON-EIE-2022-SCALEUP-02-02  0.000000e+00  HORIZON.3.2
6      HORIZON-JU-GH-EDCTP3-2022-CALL1-01-01  3.989909e+06  HORIZON.2.1
7            HORIZON-JU-GH-EDCTP3-2023-01-05  1.000000e+06  HORIZON.2.1
8             HORIZON-EIE-2022-SCALEUP-02-02  0.000000e+00  HORIZON.3.2
9             HORIZON-EIE-2022-SCALEUP-02-02  0.000000e+00  HORIZON.3.2

  ecContribution_sum netEcContribution_sum  \
0         4062396.23            4062396.23
1          500000.00             500000.00
2         6771571.00            6771571.00
3        70000000.00           70000000.00
4           75000.00              75000.00
5           75000.00              75000.00
6         3989909.25            3989909.25
7         1000000.00            1000000.00
8           75000.00              75000.00
9           75000.00              75000.00

                                 ecContribution_list  \
0                 [1777625.0, 272174.38, 2012596.85]
1  [68562.5, 91812.5, 65937.5, 42562.5, 60625.0, ...
2  [893750.0, 3478500.0, 188750.0, 766343.5, 0.0,...
3                                       [70000000.0]
4                                          [75000.0]
5                                          [75000.0]
6      [2618391.15, 388318.95, 461924.16, 521274.99]
7    [487000.0, 68000.0, 350000.0, 35000.0, 60000.0]
8                                          [75000.0]
9                                          [75000.0]

                              netEcContribution_list
0  [0.0, 1777625.0, 272174.38, 0.0, 0.0, 2012596....
1  [68562.5, 91812.5, 65937.5, 42562.5, 60625.0, ...
2  [893750.0, 0.0, 3478500.0, 188750.0, 473968.5,...
3                                       [70000000.0]
4                                          [75000.0]
5                                          [75000.0]
6      [2618391.15, 388318.95, 461924.16, 521274.99]
7    [487000.0, 68000.0, 350000.0, 35000.0, 60000.0]
8                                          [75000.0]
9                                          [75000.0]

[10 rows x 27 columns]

In [74]:
df_mda.to_excel("MordernDataAnalytics.xlsx", sheet_name="CleanedData", index=False)